// WhatsApp message composer — pure functions only.
// No DB calls, no side effects. Shared by both WEB (wa.me) and API modes.
// Money values arrive pre-formatted as strings (caller converts cents → display).

const HR = '━━━━━━━━━━━━━━━━'; // ━ × 16

/**
 * Normalise a Sri Lankan phone number to international format (no leading +
 * is required by wa.me, but we keep a canonical +94 form here).
 *   07XXXXXXXX  → +947XXXXXXXX
 *   94XXXXXXXX  → +94XXXXXXXX
 *   +94XXXXXXXX → unchanged
 * Strips spaces, dashes, brackets and dots first.
 */
export function formatPhone(phone: string): string {
  if (!phone) return '';
  // Keep a leading +, drop every other non-digit.
  const hadPlus = phone.trim().startsWith('+');
  let digits = phone.replace(/[^\d]/g, '');

  if (hadPlus) {
    // Already international — return canonical +<digits>.
    return `+${digits}`;
  }
  // 07XXXXXXXX (local) → 94 7XXXXXXXX
  if (digits.startsWith('0')) {
    digits = `94${digits.slice(1)}`;
  } else if (!digits.startsWith('94')) {
    // Bare subscriber number (e.g. 7XXXXXXXX) → prefix country code.
    digits = `94${digits}`;
  }
  return `+${digits}`;
}

export interface ReceiptData {
  invoiceNo: string;
  customerName: string;
  date: string;
  items: { name: string; qty: string; amount: string }[];
  subtotal: string;
  discount?: string;
  total: string;
  paymentMethod: string;
  businessName: string;
  phone?: string;
}

export function buildSaleReceipt(data: ReceiptData): string {
  const lines: string[] = [];
  lines.push(`*${data.businessName}*`);
  lines.push(HR);
  lines.push(`\u{1F9FE} Invoice: ${data.invoiceNo}`);
  lines.push(`\u{1F4C5} Date: ${data.date}`);
  lines.push(`\u{1F464} Customer: ${data.customerName}`);
  lines.push('');
  lines.push('*ITEMS*');
  for (const it of data.items) {
    lines.push(`${it.name} × ${it.qty} — Rs.${it.amount}`);
  }
  lines.push(HR);
  lines.push(`Subtotal: Rs.${data.subtotal}`);
  if (data.discount) lines.push(`Discount: Rs.${data.discount}`);
  lines.push(`*TOTAL: Rs.${data.total}*`);
  lines.push(`Payment: ${data.paymentMethod}`);
  lines.push('');
  lines.push('Thank you for your purchase! \u{1F64F}');
  return lines.join('\n');
}

export interface PaymentReminderData {
  customerName: string;
  invoiceNo: string;
  amount: string;
  dueDate?: string;
  businessName: string;
  businessPhone?: string;
}

export function buildPaymentReminder(data: PaymentReminderData): string {
  const lines: string[] = [];
  lines.push(`Dear ${data.customerName},`);
  lines.push('');
  lines.push('This is a friendly reminder from');
  lines.push(`*${data.businessName}*.`);
  lines.push('');
  lines.push(`\u{1F4CB} Invoice: ${data.invoiceNo}`);
  lines.push(`\u{1F4B0} Amount Due: Rs.${data.amount}`);
  if (data.dueDate) lines.push(`\u{1F4C5} Due Date: ${data.dueDate}`);
  lines.push('');
  lines.push('Please contact us to arrange payment.');
  if (data.businessPhone) lines.push(`\u{1F4DE} ${data.businessPhone}`);
  lines.push('');
  lines.push('Thank you \u{1F64F}');
  return lines.join('\n');
}

export interface DailySummaryData {
  date: string;
  totalSales: string;
  orderCount: number;
  cashCollected: string;
  creditGiven: string;
  topProduct?: string;
  newCustomers: number;
  businessName: string;
}

export function buildDailySummary(data: DailySummaryData): string {
  const lines: string[] = [];
  lines.push(`*${data.businessName} — Daily Report*`);
  lines.push(`\u{1F4C5} ${data.date}`);
  lines.push(HR);
  lines.push(`\u{1F4B0} Total Sales: Rs.${data.totalSales}`);
  lines.push(`\u{1F4E6} Orders: ${data.orderCount}`);
  lines.push(`\u{1F4B5} Cash: Rs.${data.cashCollected}`);
  lines.push(`\u{1F4D2} Credit: Rs.${data.creditGiven}`);
  if (data.topProduct) lines.push(`\u{1F3C6} Top Product: ${data.topProduct}`);
  lines.push(`\u{1F465} New Customers: ${data.newCustomers}`);
  lines.push(HR);
  lines.push('_Generated by BROcode ERP_');
  return lines.join('\n');
}

export interface LowStockData {
  products: { name: string; current: string; reorder: string }[];
  businessName: string;
}

export function buildLowStockAlert(data: LowStockData): string {
  const lines: string[] = [];
  lines.push('⚠️ *Low Stock Alert*');
  lines.push(`*${data.businessName}*`);
  lines.push('');
  lines.push('The following products need restocking:');
  lines.push('');
  for (const p of data.products) {
    lines.push(`• ${p.name}: ${p.current} (reorder at ${p.reorder})`);
  }
  lines.push('');
  lines.push('Please arrange purchase orders.');
  return lines.join('\n');
}

export interface OfferData {
  customerName: string;
  offerText: string;
  validUntil?: string;
  businessName: string;
}

export function buildOffer(data: OfferData): string {
  const lines: string[] = [];
  lines.push(`Dear ${data.customerName} \u{1F44B}`);
  lines.push('');
  lines.push(`*Special Offer from ${data.businessName}!*`);
  lines.push('');
  lines.push(data.offerText);
  if (data.validUntil) lines.push(`Valid until: ${data.validUntil}`);
  lines.push('');
  lines.push('Visit us today! \u{1F6CD}️');
  return lines.join('\n');
}

/** Same structure as buildSaleReceipt, but with Sinhala labels. */
export function buildSinhalaReceipt(data: ReceiptData): string {
  const lines: string[] = [];
  lines.push(`*${data.businessName}*`);
  lines.push(HR);
  lines.push(`\u{1F9FE} ඉන්වොය්ස්: ${data.invoiceNo}`);            // ඉන්වොයිස්
  lines.push(`\u{1F4C5} දිනය: ${data.date}`);                                                  // දිනය
  lines.push(`\u{1F464} පාරිභෝගිකයා: ${data.customerName}`); // පාරිභෝගිකයා
  lines.push('');
  lines.push('*භාණ්ඩ*'); // භාණ්ඩ (Items)
  for (const it of data.items) {
    lines.push(`${it.name} × ${it.qty} — Rs.${it.amount}`);
  }
  lines.push(HR);
  lines.push(`උප එකතුව: Rs.${data.subtotal}`); // උප එකතුව (Subtotal)
  if (data.discount) lines.push(`වට්ටම: Rs.${data.discount}`); // වට්ටම (Discount)
  lines.push(`*මුළු එකතුව: Rs.${data.total}*`); // මුළු එකතුව (Total)
  lines.push(`ගෙවීම: ${data.paymentMethod}`); // ගෙවීම (Payment)
  lines.push('');
  lines.push('ස්තූතියි \u{1F64F}'); // ස්තූතියි (Thank you)
  return lines.join('\n');
}
