CREATE TABLE "app_settings" (
  "id"                    TEXT NOT NULL,
  "businessName"          TEXT NOT NULL DEFAULT 'My Business',
  "businessRegNo"         TEXT,
  "businessAddress"       TEXT,
  "businessPhone"         TEXT,
  "businessEmail"         TEXT,
  "logoUrl"               TEXT,
  "currencySymbol"        TEXT NOT NULL DEFAULT 'Rs.',
  "currencyCode"          TEXT NOT NULL DEFAULT 'LKR',
  "currencyPosition"      TEXT NOT NULL DEFAULT 'before',
  "dateFormat"            TEXT NOT NULL DEFAULT 'DD/MM/YYYY',
  "timezone"              TEXT NOT NULL DEFAULT 'Asia/Colombo',
  "defaultTaxPercent"     DOUBLE PRECISION NOT NULL DEFAULT 0,
  "taxLabel"              TEXT NOT NULL DEFAULT 'Tax',
  "taxNumber"             TEXT,
  "taxEnabled"            BOOLEAN NOT NULL DEFAULT false,
  "taxInclusive"          BOOLEAN NOT NULL DEFAULT false,
  "posRequireShift"       BOOLEAN NOT NULL DEFAULT true,
  "posAllowDiscount"      BOOLEAN NOT NULL DEFAULT true,
  "posMaxDiscountPct"     DOUBLE PRECISION NOT NULL DEFAULT 100,
  "posPrintReceipt"       BOOLEAN NOT NULL DEFAULT true,
  "posReceiptFooter"      TEXT,
  "posDefaultWarehouseId" TEXT,
  "invoicePrefix"         TEXT NOT NULL DEFAULT 'INV',
  "invoiceStartNo"        INTEGER NOT NULL DEFAULT 1,
  "invoiceDueDays"        INTEGER NOT NULL DEFAULT 30,
  "purchasePrefix"        TEXT NOT NULL DEFAULT 'PO',
  "invoiceFooter"         TEXT,
  "invoiceShowLogo"       BOOLEAN NOT NULL DEFAULT true,
  "sessionTimeoutMin"     INTEGER NOT NULL DEFAULT 480,
  "createdAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "app_settings_pkey" PRIMARY KEY ("id")
);
