ALTER TABLE "app_settings"
  ADD COLUMN IF NOT EXISTS "receiptLanguage"    TEXT    NOT NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS "receiptTagline"     TEXT,
  ADD COLUMN IF NOT EXISTS "receiptShowLogo"    BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "receiptShowTax"     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "receiptShowSku"     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "receiptPaperWidth"  TEXT    NOT NULL DEFAULT '80mm',
  ADD COLUMN IF NOT EXISTS "receiptShowBarcode" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "receiptShowCashier" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "receiptQrEnabled"   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "receiptHeaderLine1" TEXT,
  ADD COLUMN IF NOT EXISTS "receiptHeaderLine2" TEXT;
